version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT:-5001}
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/" ]
      interval: 30s
      timeout: 5s
      retries: 3
    command: ["gunicorn", "-b", "0.0.0.0:5001", "app:app"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://backend:5001}
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://backend:5001}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/" ]
      interval: 30s
      timeout: 5s
      retries: 3

# Notes:
# - This production compose expects environment variables to be supplied via a .env file
#   or environment injection mechanism from your deployment platform.
# - It runs the backend with gunicorn (no debug / reload), and serves the frontend
#   static build with nginx listening on 8001 inside the container.
